### ISSUE TITLE
Parser isn't updating HKRPG codes?

### ISSUE THREAD

**Issue by Aida-Enna** [seriaati/hoyo-codes#52]
I haven't checked on the other games, but it looks like the API isn't returning new HKRPG (Star Rail) codes. For example, "KFWJG6L3N8M1V" was released on 10/16/2024 and is listed on prydwen's website (one of the sources), but doesn't show up in the API (https://hoyo-codes.seria.moe/codes?game=hkrpg).

EDIT: I just redeemed it manually and it is a working code.

**Comment by seriaati** [comment]
Hi, sorry for very late response, it's because I didn't notice this issue at all, I wish GitHub can have a way of notifying issues on repos... 
Anyways, as of now, the code you've mentioned (KFWJG6L3N8M1V) is still on the API, I've also checked the logs - everything seems to be working. So, I'll be closing this issue.
